# Generated by Django 2.2.6 on 2019-10-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='TrackedPosts',
        ),
    ]
